# Generated by Django 4.2.30 on 2026-07-24 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Course code (e.g., CS101, ECE201)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Course name", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Course description and syllabus"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Department offering the course", max_length=100
                    ),
                ),
                (
                    "credits",
                    models.PositiveIntegerField(default=3, help_text="Course credits"),
                ),
                ("semester", models.PositiveIntegerField(help_text="Semester (1-8)")),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=60, help_text="Maximum students allowed"
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True, help_text="Room number", max_length=50
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        help_text="Schedule (e.g., Mon/Wed 10:00-11:30)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Course instructor",
                        limit_choices_to={"role": "faculty"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taught_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["department", "semester", "code"],
            },
        ),
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("note", "Study Notes"),
                            ("slide", "Presentation"),
                            ("video", "Video Lecture"),
                            ("assignment", "Assignment"),
                            ("other", "Other"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="course_materials/"
                    ),
                ),
                (
                    "external_link",
                    models.URLField(blank=True, help_text="External link to resource"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Whether visible to students"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.course",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("dropped", "Dropped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("enrollment_date", models.DateTimeField(auto_now_add=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="Final grade (A, B+, B, C, etc.)",
                        max_length=5,
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total marks obtained",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "ordering": ["-enrollment_date"],
                "unique_together": {("student", "course")},
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="courses.course",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("student", "course", "date")},
            },
        ),
    ]
