# Generated by Django 4.2.30 on 2026-07-24 17:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Required. A valid email address.",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("faculty", "Faculty"),
                            ("student", "Student"),
                        ],
                        default="student",
                        help_text="User role in the system",
                        max_length=20,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        default="profiles/default.png",
                        help_text="User profile picture",
                        upload_to="profiles/",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact number", max_length=15
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Address")),
                (
                    "date_of_birth",
                    models.DateField(blank=True, help_text="Date of birth", null=True),
                ),
                ("bio", models.TextField(blank=True, help_text="Short biography")),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether the user email is verified"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(
                        help_text="Unique roll number", max_length=20, unique=True
                    ),
                ),
                (
                    "enrollment_number",
                    models.CharField(
                        blank=True,
                        help_text="University enrollment number",
                        max_length=30,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(help_text="Department/Branch", max_length=100),
                ),
                (
                    "year",
                    models.PositiveIntegerField(help_text="Current year (1, 2, 3, 4)"),
                ),
                (
                    "semester",
                    models.PositiveIntegerField(help_text="Current semester (1-8)"),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True, help_text="Section (A, B, C)", max_length=5
                    ),
                ),
                (
                    "batch",
                    models.CharField(
                        blank=True,
                        help_text="Batch year (e.g., 2024-2028)",
                        max_length=10,
                    ),
                ),
                (
                    "cgpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current CGPA",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "parent_name",
                    models.CharField(
                        blank=True, help_text="Parent/Guardian name", max_length=100
                    ),
                ),
                (
                    "parent_phone",
                    models.CharField(
                        blank=True, help_text="Parent contact number", max_length=15
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "student profile",
                "verbose_name_plural": "student profiles",
            },
        ),
        migrations.CreateModel(
            name="FacultyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Unique employee ID", max_length=20, unique=True
                    ),
                ),
                (
                    "department",
                    models.CharField(help_text="Department", max_length=100),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="Designation (Professor, Associate Professor, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, help_text="Area of expertise", max_length=200
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True, help_text="Highest qualification", max_length=200
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, help_text="Years of experience"
                    ),
                ),
                (
                    "office_location",
                    models.CharField(
                        blank=True, help_text="Office room number", max_length=100
                    ),
                ),
                (
                    "office_hours",
                    models.CharField(
                        blank=True,
                        help_text="Office hours (e.g., Mon-Fri 10AM-5PM)",
                        max_length=100,
                    ),
                ),
                (
                    "research_interests",
                    models.TextField(blank=True, help_text="Research interests"),
                ),
                (
                    "publications",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of publications"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "faculty profile",
                "verbose_name_plural": "faculty profiles",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Department name", max_length=100, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Department code (e.g., CSE, ECE)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department head",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "ordering": ["name"],
            },
        ),
    ]
