# Generated by Django 4.2.30 on 2026-08-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_sentence',
            field=models.CharField(blank=True, default='', help_text='Unique secret sentence used for password recovery', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number', max_length=10),
        ),
    ]
